### PR TITLE
merge PR#14, add support for protobuf, format on save now works and etc.

### PR DESCRIPTION
**Pull request by owt5008137**
these code has merged PR[#14](https://github.com/xaverh/vscode-clang-format-provider/pull/14) and add some more functions. That's

* add protobuf support(work with https://marketplace.visualstudio.com/items?itemName=peterj.proto)
* allow different style & fallback style option for different languages
* format on save is available now(just like https://github.com/Microsoft/vscode-go/blob/master/src/goMain.ts)

@xaverh , I have tested in my vscode, but please review the code because there are many changes.

### CODE REVIEW

**Comment by martine** [comment]
Is there anything I can do to assist with making a new release?  I am sorry to bug you but I'm eager to use the new version.  :)

**Comment by owt5008137** [comment]
@martine I don't  know the release plan of @xaverh ,but you can build this plugin yours self and replace the directory in $HOME/.vscode/extensions/xaver.clang-format-0.6.1 for temporary use.

$HOME is c:\\Users\\[UserNanme] in Windows 7 or later.

**Comment by xaverh** [comment]
I pushed the new version to the marketplace. Apologies for the delay, I had a very busy week. Thank you very much for your valuable contributions!

**Comment by willdzeng** [comment]
Does formatting on protobuf still works? Why doesn't it work for me? Is there any dependency that I need to install to make it work?

**Comment by xaverh** [comment]
I never used Protobuf, so I do not really know. Have you installed https://marketplace.visualstudio.com/items?itemName=peterj.proto as well?

**Comment by owt5008137** [comment]
[Protobuf support](https://marketplace.visualstudio.com/items?itemName=peterj.proto) is required if you want to format .proto files.
It works well and I have used it for a long time.

**Comment by willdzeng** [comment]
@owt5008137 
I know why now, I have [vscode-proto3](https://marketplace.visualstudio.com/items?itemName=zxh404.vscode-proto3) installed, and it seems like to have conflicts,
Any chance of making them compatible? The vscode-proto3 has better highlighting.

**Comment by owt5008137** [comment]
This plugin registers protobuf as Language:proto3 but not Language:proto. I will try to adapt it later.
After tested, I will create another RP.

**Comment by willdzeng** [comment]
@owt5008137 Thank you so much!

**Comment by owt5008137** [comment]
@willdzeng #41 has been pushed and please wait for next release of this plugin.
@xaverh

**Comment by xaverh** [comment]
... and is also available in the marketplace right now

**Pull request merged**
